apiVersion: kro.run/v1alpha1
kind: Workload
metadata:
  name: hello-api
  namespace: team-alpha-dev
spec:
  name: hello-api
  team: alpha

  containers:
    main:
      image: hello-api:v1.0.0

  service:
    ports:
      http:
        port: 8080
