apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-sa
  namespace: {{ .Values.namespace }}
  labels:
    platform.io/team: {{ .Values.team }}
    platform.io/workload: {{ .Values.name }}
