apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-capabilities
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - team: database
            chart: team-database
            revision: "1.*"
          - team: cache
            chart: team-cache
            revision: "1.*"
          - team: pubsub
            chart: team-pubsub
            revision: "1.*"
  template:
    metadata:
      name: "capability-{{team}}"
    spec:
      project: default
      source:
        chart: "{{chart}}"
        repoURL: 279051970617.dkr.ecr.us-east-1.amazonaws.com/plat-cp/charts
        targetRevision: "{{revision}}"
        helm:
          valuesObject:
            defaults:
              clusterName: plat-cp-cluster
              engineVersion: "16.14"
              dbSubnetGroupName: plat-cp-db-subnets
              cacheSubnetGroupName: plat-cp-cache-subnets
      destination:
        server: https://kubernetes.default.svc
        namespace: platform-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
